export const sourceChapterSpecs = [
  ["Home & Neighborhood", "Describe your home and neighborhood"],
  ["Work", "Talk about your job, responsibilities, and routine"],
  ["Hobbies & Free Time", "Talk about your free time and favorite activities"],
  ["Friends", "Describe your friends and relationships"],
  ["Food & Cooking", "Describe food, eating habits, and preferences"],
  ["Weekends & Daily Life", "Talk about your routine and weekends"],
  ["Shopping", "Talk about prices, products, and shopping choices"],
  ["Weather & Seasons", "Describe the weather and how it affects your life"],
  ["Travel & Holidays", "Describe trips, destinations, and travel experiences"],
  ["Music", "Talk about your favorite music and preferences"],
] as const;

type SourceWord = [
  word: string,
  definition: string,
  example: string,
  hint: string,
];

export const sourceWordCatalog: SourceWord[] = [
  [
    "spacious",
    "having a lot of room",
    "Our new apartment is bright and spacious.",
    "Think of a room with plenty of space.",
  ],
  [
    "convenient",
    "easy and useful for you",
    "Living near the train station is very convenient.",
    "Convenient saves time or effort.",
  ],
  [
    "peaceful",
    "quiet and calm",
    "I enjoy living in a peaceful neighborhood.",
    "Peaceful places are calm, not noisy.",
  ],
  [
    "lively",
    "full of activity and energy",
    "The city center is lively on Friday nights.",
    "A lively place has lots of activity.",
  ],
  [
    "surroundings",
    "the area around a place",
    "The hotel has beautiful surroundings.",
    "Look at the area around a place.",
  ],
  [
    "suitable",
    "right or good for a situation",
    "This apartment is suitable for a small family.",
    "Suitable means right for your needs.",
  ],
  [
    "atmosphere",
    "the feeling of a place",
    "The neighborhood has a friendly atmosphere.",
    "Atmosphere is the feeling a place gives you.",
  ],
  [
    "demanding",
    "needing a lot of effort or time",
    "My job can be very demanding.",
    "A demanding task needs a lot from you.",
  ],
  [
    "flexible",
    "able to change easily",
    "My company has flexible working hours.",
    "Flexible plans can change easily.",
  ],
  [
    "efficient",
    "working well without wasting time",
    "I’m more efficient in the morning.",
    "Efficient work gets good results without waste.",
  ],
  [
    "responsibility",
    "something you must take care of",
    "Training new employees is one of my responsibilities.",
    "A responsibility is something you must handle.",
  ],
  [
    "motivated",
    "wanting to work hard or succeed",
    "I feel motivated when I learn something new.",
    "Motivated people want to improve.",
  ],
  [
    "routine",
    "things you regularly do",
    "Checking my email is part of my morning routine.",
    "A routine repeats regularly.",
  ],
  [
    "challenging",
    "difficult but interesting",
    "My new project is challenging but enjoyable.",
    "A challenging task is hard but interesting.",
  ],
  [
    "creative",
    "good at making or thinking of new things",
    "Painting is a creative hobby.",
    "Creative people make new ideas or things.",
  ],
  [
    "active",
    "doing a lot of physical activity",
    "I try to stay active on weekends.",
    "Active means doing things and moving.",
  ],
  [
    "passionate",
    "very interested in something",
    "She’s passionate about photography.",
    "Passionate means very interested.",
  ],
  [
    "entertaining",
    "enjoyable or fun",
    "I thought the movie was very entertaining.",
    "Entertaining things are fun to watch or do.",
  ],
  [
    "productive",
    "getting useful things done",
    "I had a productive weekend.",
    "Productive time gets useful things done.",
  ],
  [
    "recharge",
    "rest and get your energy back",
    "I need the weekend to recharge.",
    "Recharge means rest and get energy back.",
  ],
  [
    "take up",
    "start doing a new activity",
    "I’d like to take up swimming.",
    "Take up means start a new hobby.",
  ],
  [
    "sincere",
    "honest about your feelings",
    "He gave me a sincere apology.",
    "Sincere words honestly show feelings.",
  ],
  [
    "reliable",
    "someone you can depend on",
    "She’s very reliable and always helps me.",
    "A reliable person keeps promises.",
  ],
  [
    "supportive",
    "giving help and encouragement",
    "My friends were very supportive when I changed jobs.",
    "A supportive person helps you continue.",
  ],
  [
    "considerate",
    "thinking about other people’s feelings",
    "It was considerate of him to call and check on me.",
    "Considerate people think about others.",
  ],
  [
    "outgoing",
    "friendly and enjoying meeting people",
    "My brother is very outgoing.",
    "Outgoing people enjoy meeting others.",
  ],
  [
    "reserved",
    "quiet and not showing feelings easily",
    "I’m usually reserved when I meet new people.",
    "Reserved people are quiet at first.",
  ],
  [
    "have in common",
    "share the same interests or qualities",
    "We have a lot in common, including our taste in music.",
    "People who have things in common share qualities.",
  ],
  [
    "appetite",
    "desire to eat",
    "I don’t have much of an appetite in the morning.",
    "Appetite is your desire to eat.",
  ],
  [
    "filling",
    "making you feel full",
    "Oatmeal is a very filling breakfast.",
    "Filling food makes you feel full.",
  ],
  [
    "flavor",
    "the particular taste of food",
    "This soup has a strong flavor.",
    "Flavor is the taste of food.",
  ],
  [
    "fresh",
    "recently made or prepared",
    "I prefer fresh vegetables.",
    "Fresh food was recently made or picked.",
  ],
  [
    "balanced",
    "having the right amounts of different things",
    "I try to eat a balanced diet.",
    "Balanced means the parts are in healthy amounts.",
  ],
  [
    "traditional",
    "connected to old customs",
    "My grandmother makes traditional dishes.",
    "Traditional things connect to old customs.",
  ],
  [
    "tempting",
    "making you really want something",
    "The desserts look very tempting.",
    "Tempting things make you want them.",
  ],
  [
    "productive",
    "getting useful things done",
    "Saturday was very productive.",
    "Productive time gets useful things done.",
  ],
  [
    "exhausted",
    "extremely tired",
    "I was exhausted after work.",
    "Exhausted means extremely tired.",
  ],
  [
    "energetic",
    "having lots of energy",
    "I usually feel energetic in the morning.",
    "Energetic people have lots of energy.",
  ],
  [
    "spontaneous",
    "done without planning",
    "We took a spontaneous trip to the beach.",
    "Spontaneous actions happen without a plan.",
  ],
  [
    "typical",
    "normal or usual",
    "A typical Sunday is quiet for me.",
    "Typical means normal or usual.",
  ],
  [
    "occasionally",
    "sometimes, but not often",
    "I occasionally work on weekends.",
    "Occasionally means sometimes, not often.",
  ],
  [
    "make the most of",
    "use something as well as possible",
    "I try to make the most of my weekends.",
    "Make the most of means use well.",
  ],
  [
    "affordable",
    "not too expensive",
    "I’m looking for an affordable laptop.",
    "Affordable means not too expensive.",
  ],
  [
    "reasonable",
    "fair; not too expensive",
    "The restaurant’s prices are reasonable.",
    "A reasonable price is fair.",
  ],
  [
    "quality",
    "how good something is",
    "I care more about quality than brand names.",
    "Quality describes how good something is.",
  ],
  [
    "practical",
    "useful in everyday life",
    "I usually buy practical clothes.",
    "Practical things are useful every day.",
  ],
  [
    "essential",
    "completely necessary",
    "A phone is essential for my work.",
    "Essential means completely necessary.",
  ],
  [
    "brand",
    "company or name that makes a product",
    "I usually buy the same brand of shoes.",
    "A brand is a product maker’s name.",
  ],
  [
    "worth it",
    "good enough for the money or effort",
    "The hotel was expensive, but it was worth it.",
    "Worth it means good enough for the cost.",
  ],
  [
    "humid",
    "having a lot of moisture in the air",
    "Summers here are hot and humid.",
    "Humid air has lots of moisture.",
  ],
  [
    "mild",
    "not very hot or very cold",
    "We had a mild winter this year.",
    "Mild weather is not extreme.",
  ],
  [
    "freezing",
    "extremely cold",
    "It’s freezing outside today.",
    "Freezing means extremely cold.",
  ],
  [
    "pleasant",
    "nice and enjoyable",
    "The weather was pleasant yesterday.",
    "Pleasant weather feels nice.",
  ],
  [
    "unpredictable",
    "difficult to know what will happen",
    "The weather here is unpredictable.",
    "Unpredictable things are hard to forecast.",
  ],
  [
    "forecast",
    "information about future weather",
    "I checked the weather forecast this morning.",
    "A forecast tells you what weather may come.",
  ],
  [
    "affect",
    "cause a change in something",
    "Bad weather can affect my mood.",
    "Affect means cause a change.",
  ],
  [
    "destination",
    "the place you are traveling to",
    "Spain is a popular holiday destination.",
    "A destination is where you are going.",
  ],
  [
    "memorable",
    "special and easy to remember",
    "It was a memorable vacation.",
    "Memorable moments stay in your mind.",
  ],
  [
    "adventurous",
    "willing to try new or exciting things",
    "I’m more adventurous when I travel.",
    "Adventurous people try new things.",
  ],
  [
    "crowded",
    "full of people",
    "The beach was extremely crowded.",
    "Crowded places have many people.",
  ],
  [
    "scenery",
    "natural views in an area",
    "The mountain scenery was beautiful.",
    "Scenery means natural views.",
  ],
  [
    "explore",
    "travel around to learn about a place",
    "We spent the afternoon exploring the city.",
    "Explore means look around and learn.",
  ],
  [
    "get away",
    "leave your normal life for a short break",
    "I like to get away for the weekend.",
    "Get away means take a short break elsewhere.",
  ],
  [
    "taste",
    "the kinds of things you personally like",
    "My brother and I have different tastes in music.",
    "Taste is what you personally like.",
  ],
  [
    "lyrics",
    "the words of a song",
    "I like this song because of the lyrics.",
    "Lyrics are the words in a song.",
  ],
  [
    "catchy",
    "easy to remember",
    "That song has a catchy tune.",
    "Catchy music stays in your mind.",
  ],
  [
    "relaxing",
    "making you feel calm",
    "I listen to relaxing music before bed.",
    "Relaxing things help you feel calm.",
  ],
  [
    "live",
    "performed in front of people",
    "I prefer listening to live music.",
    "Live music is performed in front of people.",
  ],
  [
    "talented",
    "naturally good at something",
    "She’s a very talented singer.",
    "Talented people are naturally good at something.",
  ],
  [
    "remind",
    "make someone remember something",
    "This song reminds me of my childhood.",
    "Remind means bring a memory back.",
  ],
];
