export const sourceChapterSpecs = [
  ['Home & Neighborhood', 'صف منزلك والحي المحيط بك'],
  ['Work', 'تحدث عن وظيفتك ومسؤولياتك وروتينك'],
  ['Hobbies & Free Time', 'تحدث عن وقت فراغك والأنشطة التي تحبها'],
  ['Friends', 'صف شخصيات أصدقائك وعلاقاتك'],
  ['Food & Cooking', 'صف الطعام وعادات الأكل وتفضيلاتك'],
  ['Weekends & Daily Life', 'تحدث عن روتينك وكيف تقضي عطلة نهاية الأسبوع'],
  ['Shopping', 'تحدث عن الأسعار والمنتجات وما تختار شراءه'],
  ['Weather & Seasons', 'صف الطقس وتأثيره على حياتك'],
  ['Travel & Holidays', 'صف الرحلات والوجهات وتجارب السفر'],
  ['Music', 'تحدث عن الموسيقى التي تحبها وتفضيلاتك'],
] as const;

type SourceWord = [string, string, string, string, string, string];

export const sourceWordCatalog: SourceWord[] = [
  ['spacious', 'واسع', 'having a lot of room', 'Our new apartment is bright and spacious.', 'شقتنا الجديدة مشرقة وواسعة.', 'Think of a room with plenty of space.'],
  ['convenient', 'مناسب', 'easy and useful for you', 'Living near the train station is very convenient.', 'السكن بالقرب من محطة القطار مناسب جدًا.', 'Convenient saves time or effort.'],
  ['peaceful', 'هادئ', 'quiet and calm', 'I enjoy living in a peaceful neighborhood.', 'أستمتع بالعيش في حي هادئ.', 'Peaceful places are calm, not noisy.'],
  ['lively', 'حيوي', 'full of activity and energy', 'The city center is lively on Friday nights.', 'وسط المدينة حيوي في ليالي الجمعة.', 'A lively place has lots of activity.'],
  ['surroundings', 'المحيط', 'the area around a place', 'The hotel has beautiful surroundings.', 'لدى الفندق محيط جميل.', 'Look at the area around a place.'],
  ['suitable', 'ملائم', 'right or good for a situation', 'This apartment is suitable for a small family.', 'هذه الشقة ملائمة لعائلة صغيرة.', 'Suitable means right for your needs.'],
  ['atmosphere', 'أجواء', 'the feeling of a place', 'The neighborhood has a friendly atmosphere.', 'للحي أجواء ودية.', 'Atmosphere is the feeling a place gives you.'],

  ['demanding', 'متطلب', 'needing a lot of effort or time', 'My job can be very demanding.', 'قد تكون وظيفتي متطلبة جدًا.', 'A demanding task needs a lot from you.'],
  ['flexible', 'مرن', 'able to change easily', 'My company has flexible working hours.', 'لدى شركتي ساعات عمل مرنة.', 'Flexible plans can change easily.'],
  ['efficient', 'فعّال', 'working well without wasting time', 'I’m more efficient in the morning.', 'أكون أكثر فعالية في الصباح.', 'Efficient work gets good results without waste.'],
  ['responsibility', 'مسؤولية', 'something you must take care of', 'Training new employees is one of my responsibilities.', 'تدريب الموظفين الجدد إحدى مسؤولياتي.', 'A responsibility is something you must handle.'],
  ['motivated', 'متحفّز', 'wanting to work hard or succeed', 'I feel motivated when I learn something new.', 'أشعر بالحماس عندما أتعلم شيئًا جديدًا.', 'Motivated people want to improve.'],
  ['routine', 'روتين', 'things you regularly do', 'Checking my email is part of my morning routine.', 'تفقد بريدي جزء من روتيني الصباحي.', 'A routine repeats regularly.'],
  ['challenging', 'مليء بالتحديات', 'difficult but interesting', 'My new project is challenging but enjoyable.', 'مشروعي الجديد مليء بالتحديات لكنه ممتع.', 'A challenging task is hard but interesting.'],

  ['creative', 'مبدع', 'good at making or thinking of new things', 'Painting is a creative hobby.', 'الرسم هواية إبداعية.', 'Creative people make new ideas or things.'],
  ['active', 'نشيط', 'doing a lot of physical activity', 'I try to stay active on weekends.', 'أحاول أن أبقى نشيطًا في عطلة نهاية الأسبوع.', 'Active means doing things and moving.'],
  ['passionate', 'شغوف', 'very interested in something', 'She’s passionate about photography.', 'هي شغوفة بالتصوير.', 'Passionate means very interested.'],
  ['entertaining', 'ممتع', 'enjoyable or fun', 'I thought the movie was very entertaining.', 'اعتقدت أن الفيلم كان ممتعًا جدًا.', 'Entertaining things are fun to watch or do.'],
  ['productive', 'منتج', 'getting useful things done', 'I had a productive weekend.', 'كانت عطلة نهاية أسبوع منتجة.', 'Productive time gets useful things done.'],
  ['recharge', 'يستعيد طاقته', 'rest and get your energy back', 'I need the weekend to recharge.', 'أحتاج إلى عطلة نهاية الأسبوع لاستعادة طاقتي.', 'Recharge means rest and get energy back.'],
  ['take up', 'يبدأ ممارسة', 'start doing a new activity', 'I’d like to take up swimming.', 'أود أن أبدأ ممارسة السباحة.', 'Take up means start a new hobby.'],

  ['sincere', 'صادق', 'honest about your feelings', 'He gave me a sincere apology.', 'قدم لي اعتذارًا صادقًا.', 'Sincere words honestly show feelings.'],
  ['reliable', 'موثوق', 'someone you can depend on', 'She’s very reliable and always helps me.', 'هي موثوقة وتساعدني دائمًا.', 'A reliable person keeps promises.'],
  ['supportive', 'داعم', 'giving help and encouragement', 'My friends were very supportive when I changed jobs.', 'كان أصدقائي داعمين عندما غيرت عملي.', 'A supportive person helps you continue.'],
  ['considerate', 'مراعٍ للآخرين', 'thinking about other people’s feelings', 'It was considerate of him to call and check on me.', 'كان من مراعاته أن يتصل ويتأكد من أخباري.', 'Considerate people think about others.'],
  ['outgoing', 'اجتماعي', 'friendly and enjoying meeting people', 'My brother is very outgoing.', 'أخي اجتماعي جدًا.', 'Outgoing people enjoy meeting others.'],
  ['reserved', 'متحفظ', 'quiet and not showing feelings easily', 'I’m usually reserved when I meet new people.', 'أكون عادةً متحفظًا عندما ألتقي أشخاصًا جددًا.', 'Reserved people are quiet at first.'],
  ['have in common', 'يشترك في', 'share the same interests or qualities', 'We have a lot in common, including our taste in music.', 'لدينا الكثير من الأمور المشتركة، ومنها ذوقنا في الموسيقى.', 'People who have things in common share qualities.'],

  ['appetite', 'شهية', 'desire to eat', 'I don’t have much of an appetite in the morning.', 'ليست لدي شهية كبيرة في الصباح.', 'Appetite is your desire to eat.'],
  ['filling', 'مشبع', 'making you feel full', 'Oatmeal is a very filling breakfast.', 'الشوفان فطور مشبع جدًا.', 'Filling food makes you feel full.'],
  ['flavor', 'نكهة', 'the particular taste of food', 'This soup has a strong flavor.', 'لهذا الحساء نكهة قوية.', 'Flavor is the taste of food.'],
  ['fresh', 'طازج', 'recently made or prepared', 'I prefer fresh vegetables.', 'أفضل الخضروات الطازجة.', 'Fresh food was recently made or picked.'],
  ['balanced', 'متوازن', 'having the right amounts of different things', 'I try to eat a balanced diet.', 'أحاول أن أتناول غذاءً متوازنًا.', 'Balanced means the parts are in healthy amounts.'],
  ['traditional', 'تقليدي', 'connected to old customs', 'My grandmother makes traditional dishes.', 'تعد جدتي أطباقًا تقليدية.', 'Traditional things connect to old customs.'],
  ['tempting', 'مغرٍ', 'making you really want something', 'The desserts look very tempting.', 'تبدو الحلويات مغرية جدًا.', 'Tempting things make you want them.'],

  ['productive', 'منتج', 'getting useful things done', 'Saturday was very productive.', 'كان يوم السبت منتجًا جدًا.', 'Productive time gets useful things done.'],
  ['exhausted', 'منهك', 'extremely tired', 'I was exhausted after work.', 'كنت منهكًا بعد العمل.', 'Exhausted means extremely tired.'],
  ['energetic', 'نشيط', 'having lots of energy', 'I usually feel energetic in the morning.', 'أشعر عادةً بالنشاط في الصباح.', 'Energetic people have lots of energy.'],
  ['spontaneous', 'عفوي', 'done without planning', 'We took a spontaneous trip to the beach.', 'قمنا برحلة عفوية إلى الشاطئ.', 'Spontaneous actions happen without a plan.'],
  ['typical', 'اعتيادي', 'normal or usual', 'A typical Sunday is quiet for me.', 'يوم الأحد الاعتيادي هادئ بالنسبة لي.', 'Typical means normal or usual.'],
  ['occasionally', 'أحيانًا', 'sometimes, but not often', 'I occasionally work on weekends.', 'أعمل أحيانًا في عطلات نهاية الأسبوع.', 'Occasionally means sometimes, not often.'],
  ['make the most of', 'يستفيد أقصى استفادة', 'use something as well as possible', 'I try to make the most of my weekends.', 'أحاول الاستفادة القصوى من عطلات نهاية الأسبوع.', 'Make the most of means use well.'],

  ['affordable', 'مناسب السعر', 'not too expensive', 'I’m looking for an affordable laptop.', 'أبحث عن حاسوب محمول مناسب السعر.', 'Affordable means not too expensive.'],
  ['reasonable', 'معقول', 'fair and not too expensive', 'The restaurant’s prices are reasonable.', 'أسعار المطعم معقولة.', 'A reasonable price is fair.'],
  ['quality', 'جودة', 'how good something is', 'I care more about quality than brand names.', 'أهتم بالجودة أكثر من أسماء العلامات التجارية.', 'Quality describes how good something is.'],
  ['practical', 'عملي', 'useful in everyday life', 'I usually buy practical clothes.', 'أشتري عادةً ملابس عملية.', 'Practical things are useful every day.'],
  ['essential', 'أساسي', 'completely necessary', 'A phone is essential for my work.', 'الهاتف أساسي لعملي.', 'Essential means completely necessary.'],
  ['brand', 'علامة تجارية', 'a company or name that makes a product', 'I usually buy the same brand of shoes.', 'أشتري عادةً العلامة التجارية نفسها من الأحذية.', 'A brand is a product maker’s name.'],
  ['worth it', 'يستحق ذلك', 'good enough for the money or effort', 'The hotel was expensive, but it was worth it.', 'كان الفندق غاليًا، لكنه كان يستحق ذلك.', 'Worth it means good enough for the cost.'],

  ['humid', 'رطب', 'having a lot of moisture in the air', 'Summers here are hot and humid.', 'الصيف هنا حار ورطب.', 'Humid air has lots of moisture.'],
  ['mild', 'معتدل', 'not very hot or very cold', 'We had a mild winter this year.', 'كان لدينا شتاء معتدل هذا العام.', 'Mild weather is not extreme.'],
  ['freezing', 'شديد البرودة', 'extremely cold', 'It’s freezing outside today.', 'الجو شديد البرودة في الخارج اليوم.', 'Freezing means extremely cold.'],
  ['pleasant', 'لطيف', 'nice and enjoyable', 'The weather was pleasant yesterday.', 'كان الطقس لطيفًا أمس.', 'Pleasant weather feels nice.'],
  ['unpredictable', 'غير متوقع', 'difficult to know what will happen', 'The weather here is unpredictable.', 'الطقس هنا غير متوقع.', 'Unpredictable things are hard to forecast.'],
  ['forecast', 'توقعات الطقس', 'information about future weather', 'I checked the weather forecast this morning.', 'تحققت من توقعات الطقس هذا الصباح.', 'A forecast tells you what weather may come.'],
  ['affect', 'يؤثر', 'cause a change in something', 'Bad weather can affect my mood.', 'يمكن للطقس السيئ أن يؤثر في مزاجي.', 'Affect means cause a change.'],

  ['destination', 'وجهة', 'the place you are traveling to', 'Spain is a popular holiday destination.', 'إسبانيا وجهة شهيرة للعطلات.', 'A destination is where you are going.'],
  ['memorable', 'لا يُنسى', 'special and easy to remember', 'It was a memorable vacation.', 'كانت عطلة لا تُنسى.', 'Memorable moments stay in your mind.'],
  ['adventurous', 'مغامر', 'willing to try new or exciting things', 'I’m more adventurous when I travel.', 'أكون أكثر مغامرة عندما أسافر.', 'Adventurous people try new things.'],
  ['crowded', 'مزدحم', 'full of people', 'The beach was extremely crowded.', 'كان الشاطئ مزدحمًا جدًا.', 'Crowded places have many people.'],
  ['scenery', 'مناظر طبيعية', 'natural views in an area', 'The mountain scenery was beautiful.', 'كانت مناظر الجبال الطبيعية جميلة.', 'Scenery means natural views.'],
  ['explore', 'يستكشف', 'travel around to learn about a place', 'We spent the afternoon exploring the city.', 'قضينا فترة بعد الظهر نستكشف المدينة.', 'Explore means look around and learn.'],
  ['get away', 'يذهب في عطلة قصيرة', 'leave normal life for a short break', 'I like to get away for the weekend.', 'أحب أن أذهب في عطلة قصيرة في نهاية الأسبوع.', 'Get away means take a short break elsewhere.'],

  ['taste', 'ذوق', 'the kinds of things you personally like', 'My brother and I have different tastes in music.', 'لدي ولأخي أذواق مختلفة في الموسيقى.', 'Taste is what you personally like.'],
  ['lyrics', 'كلمات الأغنية', 'the words of a song', 'I like this song because of the lyrics.', 'أحب هذه الأغنية بسبب كلماتها.', 'Lyrics are the words in a song.'],
  ['catchy', 'سهل التذكر', 'easy to remember', 'That song has a catchy tune.', 'تلك الأغنية لحنها سهل التذكر.', 'Catchy music stays in your mind.'],
  ['relaxing', 'باعث على الاسترخاء', 'making you feel calm', 'I listen to relaxing music before bed.', 'أستمع إلى موسيقى باعثة على الاسترخاء قبل النوم.', 'Relaxing things help you feel calm.'],
  ['live', 'مباشر', 'performed in front of people', 'I prefer listening to live music.', 'أفضل الاستماع إلى الموسيقى المباشرة.', 'Live music is performed in front of people.'],
  ['talented', 'موهوب', 'naturally good at something', 'She’s a very talented singer.', 'هي مغنية موهوبة جدًا.', 'Talented people are naturally good at something.'],
  ['remind', 'يذكّر', 'make someone remember something', 'This song reminds me of my childhood.', 'تذكرني هذه الأغنية بطفولتي.', 'Remind means bring a memory back.'],
];